name: Data Contribution (Map Markers)
description: Contribute new map marker data to the interactive map
title: "[DATA] New marker contribution"
labels: ["data-contribution"]
assignees:
  - ryoma-yama
body:
  - type: markdown
    attributes:
      value: |
        ## Data Contribution
        
        Thank you for contributing to the Daemon X Machina: Titanic Scion Interactive Map! 
        
        **How to get coordinates:**
        1. Open the interactive map in your browser
        2. Press `Shift + R` to enable Recording mode (red "REC" badge will appear)
        3. Click on map locations to get coordinates

  - type: textarea
    id: marker_data
    attributes:
      label: Marker Data
      description: |
        Provide marker information in this simple format (one per line):
        
        **Format:** `{map_id} {x} {y} {category} "{name}" "{description}"`
        
        **Available maps:** forest, desert, mountains
        **Available categories:** bgm, card, chest, enemy, log, decal
        
        **Note:** Description is optional - you can leave it empty if needed: `"{name}" ""`
        
        **Example:**
        ```
        forest 400 300 bgm "BGM Player" "Hidden music track near the waterfall"
        desert 150 450 chest "Treasure Chest" "Contains rare weapon parts"
        mountains 800 200 log "Captain's Log" ""
        ```
      placeholder: |
        forest 400 300 bgm "BGM Player" "Hidden music track near the waterfall"
        desert 150 450 chest "Treasure Chest" "Contains rare weapon parts"
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information (Optional)
      description: Any screenshots, references, or notes about these markers.
      placeholder: |
        - Screenshot: [link or description]
        - Special access conditions
        - Visual landmarks nearby

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have used Recording mode for accurate coordinates
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        **Note:** Your contribution will be reviewed and added to the map. Thank you for helping improve the interactive map!